#!/bin/python

from flask import Flask

app=Flask(__name__,static_url_path='/static')

@app.route('/')
def index():
  return app.send_static_file('index.html')

@app.route('/js/<path:path>')
def web_js(path):
  return app.send_from_directory('js',path)

if __name__=="__main__":
  app.run(host='0.0.0.0')

